name: test-apps

services:
  backend:
    build: ./backend
    restart: always
    networks:
      - net-test-apps
    ports:
      - 8082:8082
    volumes:
      - vol-backend:/test-apps/backend/data/
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    networks:
      - net-test-apps
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=root
    volumes:
      - vol-postgres:/var/lib/postgresql/data/

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 8083:80
    volumes:
      - vol-frontend:/test-apps/frontend/data
    depends_on:
      - backend
volumes:
  vol-backend:
  vol-postgres:
  vol-frontend:
networks:
  net-test-apps:
    driver: bridge
