name: test-apps

services:
  backend:
    build: ./backend
    ports:
      - 8082:8082
    volumes:
      - vol-backend:/test-app/backend/data/
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=root
    volumes:
      - vol-postgres:/var/lib/postgresql/data/

volumes:
  vol-backend:
  vol-postgres:
