name: test-apps

services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - vol-backend:./backend/data
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=root
    volumes:
      - vol-postgres:/var/lib/postgresql/data

volumes:
  vol-backend:
  vol-postgres:
